name: Deploy image to AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login-to-amazon-ecr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::677615602730:role/github-actions
          aws-region: us-east-1
          mask-aws-account-id: 'false'
      -
        name: Build and push
        env:
          REGISTRY: public.ecr.aws
          REGISTRY_ALIAS: z6s0c3o0
          REPOSITORY: my-porfolio
          IMAGE_TAG: latest
        run: |
          docker build -f ../../ -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG 
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG