name: Destroy infrastructure on AWS

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["deploy/remove/**"]
  pull_request:
    branches: [main]
    paths: ["deploy/remove/**"]

jobs:
  destroy-infra-on-AWS:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::677615602730:role/github-actions
          aws-region: us-east-1
          mask-aws-account-id: 'true'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: deploy/remove

      - name: Terraform Import
        run: |
          terraform import aws_vpc.my-portfolio vpc-12345678
          terraform import aws_internet_gateway.my-portfolio igw-12345678
          terraform import aws_subnet.my-portfolio-1 subnet-12345678
          terraform import aws_subnet.my-portfolio-2 subnet-87654321
          terraform import aws_security_group.my-portfolio sg-12345678
          terraform import aws_lb.my-portfolio lb-12345678
          terraform import aws_lb_target_group.my-portfolio tg-12345678
          terraform import aws_lb_listener.my-portfolio listener-12345678
          terraform import aws_ecs_cluster.default my-portfolio
          terraform import aws_ecs_task_definition.task my-portfolio
          terraform import aws_ecs_service.service my-portfolio
        working-directory: deploy/remove

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: deploy/remove
